# Generated by Django 3.0.8 on 2021-01-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='civil_state',
            field=models.CharField(choices=[('1', 'Soltero'), ('2', 'Casado'), ('3', 'Unión libre'), ('4', 'Viudo'), ('5', 'Divorciado'), ('6', 'Separado')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='economical_situation',
            field=models.CharField(choices=[('0', 'Bajo'), ('1', 'Medio-bajo'), ('2', 'Mediano'), ('3', 'Medio-alto'), ('4', 'Alto')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='job',
            field=models.CharField(choices=[('1', 'Sin ocupación'), ('2', 'Estudios'), ('3', 'Amo(a) de casa'), ('4', 'Empleado(a) de empresa'), ('5', 'Oficio o técnico'), ('6', 'Emprendedor(a)'), ('7', 'Profesionista')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='religion',
            field=models.CharField(choices=[('1', 'Ninguna'), ('2', 'Católica'), ('3', 'Cristiano'), ('4', 'Adventista'), ('5', 'Ateo/Agnóstico'), ('6', 'Otro')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sex',
            field=models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='study',
            field=models.CharField(choices=[('1', 'Sin estudios'), ('2', 'Secundaria o menor'), ('3', 'Media Superior'), ('4', 'Superior'), ('5', 'Posgrado')], default=1, max_length=1),
        ),
    ]
