# Generated by Django 3.1.4 on 2021-01-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suicidio', models.BooleanField(default=False)),
                ('Depresion', models.BooleanField(default=False)),
                ('Distimia', models.BooleanField(default=False)),
                ('Melancolico', models.BooleanField(default=False)),
                ('Atipico', models.BooleanField(default=False)),
                ('Catatonico', models.BooleanField(default=False)),
                ('beck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.beck')),
            ],
        ),
    ]
