# Generated by Django 3.1.4 on 2021-01-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_auto_20210109_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
