# Generated by Django 3.1.4 on 2021-01-10 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctores', '0003_auto_20210109_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beck',
            old_name='paciente',
            new_name='id_paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
