# Generated by Django 3.1.4 on 2021-01-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0004_auto_20210109_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id_doctor',
        ),
    ]
