# Generated by Django 3.1.4 on 2021-01-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0006_auto_20210110_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beck',
            old_name='id_paciente',
            new_name='paciente',
        ),
    ]
