# Generated by Django 3.1.4 on 2021-01-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0008_paciente_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='beck',
            name='abuso_sexual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='conflicto_amoroso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='conflicto_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='conflicto_laboral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='dias_festivos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='divorcio_padres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='muerte_ser_querido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='perdida_trabajo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='presion_redes_sociales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='separacion_conyugal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beck',
            name='vivir_solo',
            field=models.BooleanField(default=False),
        ),
    ]
