# Generated by Django 3.1.2 on 2021-01-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0009_auto_20210116_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='civil_state',
            field=models.CharField(choices=[(0, 'Soltero'), (1, 'Casado'), (2, 'Viudo'), (3, 'Divorciado'), (4, 'Unión libre'), (5, 'Separado')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='job',
            field=models.CharField(choices=[(0, 'Sin ocupación'), (1, 'Estudios'), (2, 'Amo(a) de casa'), (3, 'Empleado(a) de empresa'), (4, 'Oficio o técnico'), (5, 'Emprendedor(a)'), (6, 'Profesionista')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='religion',
            field=models.CharField(choices=[(0, 'Católica'), (1, 'Cristiano'), (2, 'Ateo/Agnóstico'), (3, 'Adventista'), (4, 'Otro'), (5, 'Ninguna')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sex',
            field=models.CharField(choices=[(0, 'Hombre'), (1, 'Mujer')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='study',
            field=models.CharField(choices=[(0, 'Sin estudios'), (1, 'Secundaria o menor'), (2, 'Media Superior'), (3, 'Superior'), (4, 'Posgrado')], default=1, max_length=1),
        ),
    ]
