# Generated by Django 3.1.4 on 2021-01-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0012_auto_20210116_2224'),
        ('doctores', '0009_auto_20210116_2044'),
    ]

    operations = [
    ]
